############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Service
metadata:
  name: android-emulator-service-adb
  namespace: android-emulator
spec:
  type: NodePort
  selector:
    app: android-emulator
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
    nodePort: 30555
---
apiVersion: v1
kind: Service
metadata:
  name: android-emulator-service-ui
  namespace: android-emulator
spec:
  type: NodePort
  selector:
    app: android-emulator
  ports:
  - protocol: TCP
    port: 6080
    targetPort: 6080
    nodePort: 30680
---